# Generated by Django 2.2.1 on 2019-06-02 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('attack', models.IntegerField(blank=True, null=True, verbose_name='Attack')),
                ('defense', models.IntegerField(blank=True, null=True, verbose_name='Defense')),
                ('mana', models.IntegerField(blank=True, null=True, verbose_name='Mana')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='AuDigest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_id', models.IntegerField(verbose_name='lotId')),
                ('condition', models.IntegerField(blank=True, choices=[(0, 'Regular'), (1, 'Broken'), (2, 'Reinforced')], null=True, verbose_name='Condition')),
                ('status', models.IntegerField(blank=True, choices=[(0, 'Active'), (1, 'Finished'), (2, 'Cancelled')], null=True, verbose_name='Status')),
                ('quality', models.IntegerField(blank=True, choices=[(0, 'Fine'), (1, 'High'), (2, 'Great'), (3, 'Excellent')], null=True, verbose_name='quality')),
                ('end_at', models.DateTimeField(verbose_name='endAt')),
                ('started_at', models.DateTimeField(verbose_name='startedAt')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='finishedAt')),
                ('seller_castle', models.CharField(max_length=2, verbose_name='sellerCastle')),
                ('buyer_castle', models.CharField(blank=True, max_length=2, null=True, verbose_name='buyerCastle')),
                ('prince', models.IntegerField(verbose_name='price')),
                ('item_bonus', models.IntegerField(blank=True, null=True, verbose_name='Item Plus Bonus')),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to='database.Player', verbose_name='Buyer')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='database.Item', verbose_name='Item')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller', to='database.Player', verbose_name='Seller')),
            ],
        ),
    ]
